services:
  tpi-stock-client:
    container_name: tpi-stock-client
    image: tpi-stock-client
    build: 
      context: ./client
    ports:
      - "3000:3000"
    develop:
      watch:
        - path: ./client/package.json
          action: rebuild
        - path: ./client/
          target: /app
          action: sync

  tpi-stock-server:
    container_name: tpi-stock-server
    image: tpi-stock-server
    build: 
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/database:/app/database
    environment:
      - DB_CONNECTION_STRING=sqlite:////app/database/db.sqlite
    develop:
      watch:
        - path: ./server/requirements.txt
          action: rebuild
        - path: ./server/
          target: /app
          action: sync

  tpi-stock-cypress:
    container_name: tpi-stock-cypress
    image: cypress/
    build: 
      context: ./ui-testing/
    ports:
      - "3001:3001"
    develop:
      watch:
        - path: ./ui-testing/
          target: /e2e
          action: sync

volumes:
  database: