interface TextsHolder {
  createPhysicalHolder: string;
  createSimplifiedHolder: string;
  holderId: string;
  title: string;
  surname: string;
  name: string;
  birthName: string;
  birthDate: string;
  language: string;
  country: string;
  locality: string;
  npa: string;
  street: string;
  number: string;
  complement: string;
  mailAdress: string;
  facturationAdress: string;
  refundAdress: string;
  validFrom: string;
  validTo: string;
  origin: string;
  commune: string;
  secondCommune: string;
  statusTitle: string;
  status: string;
  faber: string;
  mofis: string;
  domicilPhone: string;
  workPhone: string;
  portablePhone: string;
  fax: string;
  domicilEmail: string;
  workEmail: string;
  website: string;
  facturationPeriod: string;
  facturationMode: string;
  exoneration: string;
  suspension: string;
  warning: string;
  imposition: string;
  impositionPeriod: string;
  validate: string;
  modifications: string[];
}

export default TextsHolder;